/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/test/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수강신청 시뮬레이션 실행
         * @description 모든 학생의 bestBucket에 대해 수강신청 시뮬레이션을 실행합니다.
         */
        post: operations["runSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 테스트 결과 전체 리스트 조회
         * @description 현재 로그인한 학생의 모든 테스트 결과 요약 정보를 조회합니다.
         */
        get: operations["getStudentTestResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/results/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 테스트 결과 상세 조회
         * @description 현재 로그인한 학생의 특정 테스트 결과를 상세하게 조회합니다.
         */
        get: operations["getStudentTestDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseResponseSimulationResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SimulationResultDTO"];
        };
        SimulationResultDTO: {
            /** Format: int64 */
            testId?: number;
            /** Format: int32 */
            totalStudents?: number;
            /** Format: int32 */
            totalSuccess?: number;
            /** Format: int32 */
            totalFail?: number;
            message?: string;
        };
        BaseResponseListTestSummaryDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TestSummaryDTO"][];
        };
        TestSummaryDTO: {
            /** Format: int64 */
            testId?: number;
            /** Format: date-time */
            testDate?: string;
            /** Format: int32 */
            totalCourses?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failCount?: number;
        };
        BaseResponseTestDetailDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["TestDetailDTO"];
        };
        CourseResultDTO: {
            courseName?: string;
            className?: string;
            professorName?: string;
            /** Format: float */
            credit?: number;
            isSuccess?: boolean;
            failedReason?: string;
            /** Format: int32 */
            priority?: number;
        };
        TestDetailDTO: {
            /** Format: int64 */
            testId?: number;
            /** Format: date-time */
            testDate?: string;
            studentName?: string;
            bucketName?: string;
            /** Format: int32 */
            totalCourses?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failCount?: number;
            /** Format: float */
            plannedCredit?: number;
            /** Format: float */
            earnedCredit?: number;
            courses?: components["schemas"]["CourseResultDTO"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BaseResponseSimulationResultDTO"];
                };
            };
        };
    };
    getStudentTestResults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BaseResponseListTestSummaryDTO"];
                };
            };
        };
    };
    getStudentTestDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 테스트 ID */
                testId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BaseResponseTestDetailDTO"];
                };
            };
        };
    };
}
